import type { Database } from "@/integrations/supabase/types";

// Re-export the generated Database type so app code can import a single path.
export type { Database } from "@/integrations/supabase/types";

// NOTE: The generated `Database` type file (src/integrations/supabase/types.ts)
// is auto-regenerated by Lovable Cloud whenever the schema changes. After the
// next regeneration these `Tables<'...'>` lookups will resolve to real row
// shapes; for now they resolve to `never` (the placeholder), which is safe.
type PublicSchema = Database["public"];
type TableRow<T extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][T] extends { Row: infer R } ? R : never;
type TableInsert<T extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][T] extends { Insert: infer I } ? I : never;
type TableUpdate<T extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][T] extends { Update: infer U } ? U : never;

// Domain enums (kept in sync with the SQL CHECK constraints)
export type UserLanguage = "bs" | "en" | "de";
export type UserType = "standard" | "premium" | "admin" | "super_admin";
export type ApplicationStatus = "active" | "coming_soon" | "archived";
export type SubscriptionStatus = "active" | "expired" | "cancelled" | "pending";
export type PaymentStatus = "pending" | "success" | "failed" | "refunded";
export type PaymentMethod = "stripe" | "paypal";
export type NotificationType = "info" | "success" | "warning" | "error";

// Table aliases. These resolve to real row shapes once the Supabase
// generated types (src/integrations/supabase/types.ts) are regenerated.
export type ProfileRow = TableRow<"profiles">;
export type ProfileInsert = TableInsert<"profiles">;
export type ProfileUpdate = TableUpdate<"profiles">;

export type PremiumProfileRow = TableRow<"premium_profiles">;
export type PremiumProfileInsert = TableInsert<"premium_profiles">;
export type PremiumProfileUpdate = TableUpdate<"premium_profiles">;

export type ApplicationRow = TableRow<"applications">;
export type ApplicationInsert = TableInsert<"applications">;
export type ApplicationUpdate = TableUpdate<"applications">;

export type SubscriptionPlanRow = TableRow<"subscription_plans">;
export type SubscriptionPlanInsert = TableInsert<"subscription_plans">;

export type SubscriptionRow = TableRow<"subscriptions">;
export type SubscriptionInsert = TableInsert<"subscriptions">;

export type PaymentRow = TableRow<"payments">;
export type PaymentInsert = TableInsert<"payments">;

export type NotificationRow = TableRow<"notifications">;
export type NotificationInsert = TableInsert<"notifications">;

export type AuditLogRow = TableRow<"audit_logs">;