/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as PaymentSuccessRouteImport } from './routes/payment.success'
import { Route as DashboardSubscriptionsRouteImport } from './routes/dashboard.subscriptions'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as AdminVerificationRouteImport } from './routes/admin.verification'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminCommunicationRouteImport } from './routes/admin.communication'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as UUsernameShareRouteImport } from './routes/u.$username.share'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'
import { Route as ApiPublicWebhooksPaypalRouteImport } from './routes/api/public/webhooks/paypal'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSubscriptionsRoute = DashboardSubscriptionsRouteImport.update({
  id: '/dashboard/subscriptions',
  path: '/dashboard/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/dashboard/notifications',
  path: '/dashboard/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunicationRoute = AdminCommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const UUsernameShareRoute = UUsernameShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => UUsernameRoute,
} as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksPaypalRoute = ApiPublicWebhooksPaypalRouteImport.update({
  id: '/api/public/webhooks/paypal',
  path: '/api/public/webhooks/paypal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/communication': typeof AdminCommunicationRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subscriptions': typeof DashboardSubscriptionsRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/u/$username': typeof UUsernameRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/u/$username/share': typeof UUsernameShareRoute
  '/api/public/webhooks/paypal': typeof ApiPublicWebhooksPaypalRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/communication': typeof AdminCommunicationRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subscriptions': typeof DashboardSubscriptionsRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/u/$username': typeof UUsernameRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/u/$username/share': typeof UUsernameShareRoute
  '/api/public/webhooks/paypal': typeof ApiPublicWebhooksPaypalRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/communication': typeof AdminCommunicationRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subscriptions': typeof DashboardSubscriptionsRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/u/$username': typeof UUsernameRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/u/$username/share': typeof UUsernameShareRoute
  '/api/public/webhooks/paypal': typeof ApiPublicWebhooksPaypalRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/admin/applications'
    | '/admin/communication'
    | '/admin/payments'
    | '/admin/users'
    | '/admin/verification'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/subscriptions'
    | '/payment/success'
    | '/profile/$username'
    | '/u/$username'
    | '/dashboard/'
    | '/u/$username/share'
    | '/api/public/webhooks/paypal'
    | '/api/public/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/admin/applications'
    | '/admin/communication'
    | '/admin/payments'
    | '/admin/users'
    | '/admin/verification'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/subscriptions'
    | '/payment/success'
    | '/profile/$username'
    | '/u/$username'
    | '/dashboard'
    | '/u/$username/share'
    | '/api/public/webhooks/paypal'
    | '/api/public/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/admin/applications'
    | '/admin/communication'
    | '/admin/payments'
    | '/admin/users'
    | '/admin/verification'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/subscriptions'
    | '/payment/success'
    | '/profile/$username'
    | '/u/$username'
    | '/dashboard/'
    | '/u/$username/share'
    | '/api/public/webhooks/paypal'
    | '/api/public/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSubscriptionsRoute: typeof DashboardSubscriptionsRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  UUsernameRoute: typeof UUsernameRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  ApiPublicWebhooksPaypalRoute: typeof ApiPublicWebhooksPaypalRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/subscriptions': {
      id: '/dashboard/subscriptions'
      path: '/dashboard/subscriptions'
      fullPath: '/dashboard/subscriptions'
      preLoaderRoute: typeof DashboardSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/dashboard/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communication': {
      id: '/admin/communication'
      path: '/communication'
      fullPath: '/admin/communication'
      preLoaderRoute: typeof AdminCommunicationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/u/$username/share': {
      id: '/u/$username/share'
      path: '/share'
      fullPath: '/u/$username/share'
      preLoaderRoute: typeof UUsernameShareRouteImport
      parentRoute: typeof UUsernameRoute
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/paypal': {
      id: '/api/public/webhooks/paypal'
      path: '/api/public/webhooks/paypal'
      fullPath: '/api/public/webhooks/paypal'
      preLoaderRoute: typeof ApiPublicWebhooksPaypalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminCommunicationRoute: typeof AdminCommunicationRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerificationRoute: typeof AdminVerificationRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminCommunicationRoute: AdminCommunicationRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerificationRoute: AdminVerificationRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface UUsernameRouteChildren {
  UUsernameShareRoute: typeof UUsernameShareRoute
}

const UUsernameRouteChildren: UUsernameRouteChildren = {
  UUsernameShareRoute: UUsernameShareRoute,
}

const UUsernameRouteWithChildren = UUsernameRoute._addFileChildren(
  UUsernameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSubscriptionsRoute: DashboardSubscriptionsRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  UUsernameRoute: UUsernameRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  ApiPublicWebhooksPaypalRoute: ApiPublicWebhooksPaypalRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
